"""
Approvals API - Shopping List Approval Workflow

Endpoints for viewing and approving shopping lists generated by the Inventory Agent.
"""

from typing import Optional, List
from fastapi import APIRouter, HTTPException, Depends, Query
from pydantic import BaseModel
import logging

from app.services.shopping_list_service import get_shopping_list_service
from app.utils.response import success_response, error_response, paginated_response
from app.core.dependencies import get_current_user
from app.models.user import UserResponse, UserRole

logger = logging.getLogger(__name__)
router = APIRouter()


# Request models
class ApprovalRequest(BaseModel):
    """Approval or rejection request body"""
    notes: Optional[str] = None


class PartialApprovalRequest(BaseModel):
    """Partial approval request body"""
    material_ids: List[str]
    notes: Optional[str] = None


@router.get("/pending")
async def get_pending_approvals(
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get all pending shopping lists requiring approval

    Returns:
        List of pending shopping lists with summary info
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approvals"
        )

    try:
        service = get_shopping_list_service()
        lists = await service.get_pending_shopping_lists()

        return success_response(
            data=lists,
            message=f"Found {len(lists)} pending shopping lists"
        )

    except Exception as e:
        logger.error(f"Failed to fetch pending approvals: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch pending approvals",
            details={"error": str(e)}
        )


@router.get("/history")
async def get_approval_history(
    page: int = Query(1, ge=1, description="Page number"),
    limit: int = Query(20, ge=1, le=100, description="Items per page"),
    status: Optional[str] = Query(
        None,
        regex="^(pending|approved|rejected|partially_approved)$",
        description="Filter by status"
    ),
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get approval history audit log

    Args:
        page: Page number (1-indexed)
        limit: Items per page (1-100)
        status: Optional status filter

    Returns:
        Paginated list of shopping lists
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approval history"
        )

    try:
        service = get_shopping_list_service()

        # Calculate skip
        skip = (page - 1) * limit

        # Get history
        lists = await service.get_approval_history(
            limit=limit,
            skip=skip,
            status=status
        )

        # Get total count
        total = await service.count_by_status(status)

        return paginated_response(
            data=lists,
            page=page,
            limit=limit,
            total=total
        )

    except Exception as e:
        logger.error(f"Failed to fetch approval history: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch approval history",
            details={"error": str(e)}
        )


@router.get("/stats")
async def get_approval_stats(
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get approval statistics

    Returns:
        Count of shopping lists by status
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approval statistics"
        )

    try:
        service = get_shopping_list_service()

        # Get counts by status
        pending = await service.count_by_status("pending")
        approved = await service.count_by_status("approved")
        rejected = await service.count_by_status("rejected")
        partially_approved = await service.count_by_status("partially_approved")

        return success_response(
            data={
                "pending": pending,
                "approved": approved,
                "rejected": rejected,
                "partially_approved": partially_approved,
                "total": pending + approved + rejected + partially_approved
            },
            message="Approval statistics retrieved successfully"
        )

    except Exception as e:
        logger.error(f"Failed to fetch approval stats: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch approval statistics",
            details={"error": str(e)}
        )


@router.get("/{list_id}")
async def get_shopping_list_details(
    list_id: str,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get detailed shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list

    Returns:
        Complete shopping list with all items, supplier breakdown, etc.
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approvals"
        )

    try:
        service = get_shopping_list_service()
        shopping_list = await service.get_shopping_list(list_id)

        if not shopping_list:
            return error_response(
                code="NOT_FOUND",
                message="Shopping list not found"
            )

        return success_response(
            data=shopping_list,
            message="Shopping list retrieved successfully"
        )

    except Exception as e:
        logger.error(f"Failed to fetch shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch shopping list",
            details={"error": str(e)}
        )


@router.post("/{list_id}/approve")
async def approve_shopping_list(
    list_id: str,
    request: ApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Approve entire shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Approval request with optional notes

    Returns:
        Success confirmation
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can approve shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.approve_list(
            list_id,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="APPROVAL_FAILED",
                message="Shopping list not found or already processed"
            )

        return success_response(
            data={"approved": True, "list_id": list_id},
            message="Shopping list approved successfully"
        )

    except Exception as e:
        logger.error(f"Failed to approve shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="APPROVAL_FAILED",
            message="Failed to approve shopping list",
            details={"error": str(e)}
        )


@router.post("/{list_id}/approve-items")
async def approve_shopping_list_items(
    list_id: str,
    request: PartialApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Approve specific items in shopping list (partial approval)

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Partial approval request with material IDs and optional notes

    Returns:
        Count of approved items
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can approve shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.approve_items(
            list_id,
            request.material_ids,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="APPROVAL_FAILED",
                message="Shopping list not found or items already processed"
            )

        return success_response(
            data={
                "approved_items": len(request.material_ids),
                "list_id": list_id
            },
            message=f"Approved {len(request.material_ids)} items"
        )

    except Exception as e:
        logger.error(f"Failed to approve items in list {list_id}: {e}", exc_info=True)
        return error_response(
            code="APPROVAL_FAILED",
            message="Failed to approve items",
            details={"error": str(e)}
        )


@router.post("/{list_id}/reject")
async def reject_shopping_list(
    list_id: str,
    request: ApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Reject shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Rejection request with optional notes

    Returns:
        Success confirmation
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can reject shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.reject_list(
            list_id,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="REJECTION_FAILED",
                message="Shopping list not found or already processed"
            )

        return success_response(
            data={"rejected": True, "list_id": list_id},
            message="Shopping list rejected"
        )

    except Exception as e:
        logger.error(f"Failed to reject shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="REJECTION_FAILED",
            message="Failed to reject shopping list",
            details={"error": str(e)}
        )
