"""
Approvals API - Shopping List Approval Workflow

Endpoints for viewing and approving shopping lists generated by the Inventory Agent.
"""

from datetime import datetime
from app.utils.timezone import now_ist
from typing import Optional, List, Literal
from fastapi import APIRouter, HTTPException, Depends, Query
from pydantic import BaseModel, Field
from bson import ObjectId
import logging

import asyncio
from app.services.shopping_list_service import get_shopping_list_service
from app.core.database import get_database
from app.utils.response import success_response, error_response, paginated_response
from app.core.dependencies import get_current_user, get_admin_user
from app.models.user import UserResponse, UserRole

logger = logging.getLogger(__name__)
router = APIRouter()


# Request models
class ApprovalRequest(BaseModel):
    """Approval or rejection request body"""
    notes: Optional[str] = None


class PartialApprovalRequest(BaseModel):
    """Partial approval request body"""
    material_ids: List[str]
    notes: Optional[str] = None


class POItemDecision(BaseModel):
    """Single per-item decision in a PO review"""
    material_id: str
    action: Literal["approve", "reject"]
    quantity: Optional[float] = Field(None, description="Approved quantity (for approve action)")
    reason: Optional[str] = Field(None, description="Rejection reason (for reject action)")


class POReviewRequest(BaseModel):
    """Option B per-item PO review request"""
    items: List[POItemDecision]


@router.get("/pending")
async def get_pending_approvals(
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get all pending shopping lists requiring approval

    Returns:
        List of pending shopping lists with summary info
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approvals"
        )

    try:
        service = get_shopping_list_service()
        lists = await service.get_pending_shopping_lists()

        return success_response(
            data=lists,
            message=f"Found {len(lists)} pending shopping lists"
        )

    except Exception as e:
        logger.error(f"Failed to fetch pending approvals: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch pending approvals",
            details={"error": str(e)}
        )


@router.get("/history")
async def get_approval_history(
    page: int = Query(1, ge=1, description="Page number"),
    limit: int = Query(20, ge=1, le=100, description="Items per page"),
    status: Optional[str] = Query(
        None,
        regex="^(pending|approved|rejected|partially_approved)$",
        description="Filter by status"
    ),
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get approval history audit log

    Args:
        page: Page number (1-indexed)
        limit: Items per page (1-100)
        status: Optional status filter

    Returns:
        Paginated list of shopping lists
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approval history"
        )

    try:
        service = get_shopping_list_service()

        # Calculate skip
        skip = (page - 1) * limit

        # Get history
        lists = await service.get_approval_history(
            limit=limit,
            skip=skip,
            status=status
        )

        # Get total count
        total = await service.count_by_status(status)

        return paginated_response(
            data=lists,
            page=page,
            limit=limit,
            total=total
        )

    except Exception as e:
        logger.error(f"Failed to fetch approval history: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch approval history",
            details={"error": str(e)}
        )


@router.get("/stats")
async def get_approval_stats(
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get approval statistics

    Returns:
        Count of shopping lists by status
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approval statistics"
        )

    try:
        service = get_shopping_list_service()

        # Get counts by status
        pending = await service.count_by_status("pending")
        approved = await service.count_by_status("approved")
        rejected = await service.count_by_status("rejected")
        partially_approved = await service.count_by_status("partially_approved")

        return success_response(
            data={
                "pending": pending,
                "approved": approved,
                "rejected": rejected,
                "partially_approved": partially_approved,
                "total": pending + approved + rejected + partially_approved
            },
            message="Approval statistics retrieved successfully"
        )

    except Exception as e:
        logger.error(f"Failed to fetch approval stats: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch approval statistics",
            details={"error": str(e)}
        )


@router.get("/hyperpure-orders")
async def get_hyperpure_orders(
    status: Optional[str] = Query(None, description="Filter by status: pending, fully_received"),
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Return all purchase orders placed via Hyperpure (source=hyperpure).
    Read-only — used by the Hyperpure Orders tracking page.
    """
    try:
        from app.repositories.purchase_order_repository import get_purchase_order_repository
        repo = get_purchase_order_repository()
        collection = repo._get_collection()

        query: dict = {"source": "hyperpure"}
        if status:
            query["status"] = status

        cursor = collection.find(query).sort("created_at", -1).limit(200)
        orders = await cursor.to_list(length=200)
        for o in orders:
            o["_id"] = str(o["_id"])
            for field in ("ordered_at", "delivered_at", "created_at", "updated_at"):
                if field in o and hasattr(o[field], "isoformat"):
                    o[field] = o[field].isoformat()

        return success_response(data=orders, message=f"Found {len(orders)} Hyperpure orders")

    except Exception as e:
        logger.error(f"Failed to fetch Hyperpure orders: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch Hyperpure orders",
            details={"error": str(e)},
        )


@router.get("/{list_id}")
async def get_shopping_list_details(
    list_id: str,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Get detailed shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list

    Returns:
        Complete shopping list with all items, supplier breakdown, etc.
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can view approvals"
        )

    try:
        service = get_shopping_list_service()
        shopping_list = await service.get_shopping_list(list_id)

        if not shopping_list:
            return error_response(
                code="NOT_FOUND",
                message="Shopping list not found"
            )

        return success_response(
            data=shopping_list,
            message="Shopping list retrieved successfully"
        )

    except Exception as e:
        logger.error(f"Failed to fetch shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="FETCH_FAILED",
            message="Failed to fetch shopping list",
            details={"error": str(e)}
        )


@router.post("/{list_id}/approve")
async def approve_shopping_list(
    list_id: str,
    request: ApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Approve entire shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Approval request with optional notes

    Returns:
        Success confirmation
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can approve shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.approve_list(
            list_id,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="APPROVAL_FAILED",
                message="Shopping list not found or already processed"
            )

        # Fire Hyperpure order execution in background (non-blocking)
        from app.services.orchestrator import get_orchestrator
        asyncio.create_task(get_orchestrator().execute_approved_order(list_id))

        return success_response(
            data={"approved": True, "list_id": list_id},
            message="Shopping list approved — placing order on Hyperpure"
        )

    except Exception as e:
        logger.error(f"Failed to approve shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="APPROVAL_FAILED",
            message="Failed to approve shopping list",
            details={"error": str(e)}
        )


@router.post("/{list_id}/approve-items")
async def approve_shopping_list_items(
    list_id: str,
    request: PartialApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Approve specific items in shopping list (partial approval)

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Partial approval request with material IDs and optional notes

    Returns:
        Count of approved items
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can approve shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.approve_items(
            list_id,
            request.material_ids,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="APPROVAL_FAILED",
                message="Shopping list not found or items already processed"
            )

        from app.services.orchestrator import get_orchestrator
        asyncio.create_task(get_orchestrator().execute_approved_order(list_id))

        return success_response(
            data={
                "approved_items": len(request.material_ids),
                "list_id": list_id
            },
            message=f"Approved {len(request.material_ids)} items"
        )

    except Exception as e:
        logger.error(f"Failed to approve items in list {list_id}: {e}", exc_info=True)
        return error_response(
            code="APPROVAL_FAILED",
            message="Failed to approve items",
            details={"error": str(e)}
        )


@router.post("/purchase-orders/{po_id}/review")
async def review_purchase_order(
    po_id: str,
    request: POReviewRequest,
    current_user: UserResponse = Depends(get_admin_user)
):
    """
    Apply per-item approve/reject decisions to a purchase order (Option B).

    Partial submissions are valid — undecided items remain pending.
    Owner can call this multiple times until all items have a decision.

    Args:
        po_id: MongoDB ObjectId of the shopping list (PO)
        request: List of per-item decisions

    Returns:
        Summary with approved/rejected/pending counts and approved total
    """
    try:
        service = get_shopping_list_service()
        item_decisions = [d.model_dump() for d in request.items]

        result = await service.review_po_items(
            po_id,
            item_decisions,
            str(current_user.id)
        )

        if result is None:
            return error_response(
                code="NOT_FOUND",
                message="Purchase order not found"
            )

        # Fire Hyperpure order execution in background (non-blocking)
        # This will pick up any items newly marked as 'approved'
        from app.services.orchestrator import get_orchestrator
        asyncio.create_task(get_orchestrator().execute_approved_order(po_id))

        return success_response(
            data={
                "po_id": po_id,
                "status": result["list_status"],
                "approved_items": result["approved"],
                "rejected_items": result["rejected"],
                "pending_items": result["pending"],
                "approved_total_paise": result["approved_total_paise"],
            },
            message="Purchase order decisions recorded"
        )

    except ValueError as e:
        return error_response(
            code="INVALID_STATE",
            message=str(e)
        )
    except Exception as e:
        logger.error(f"Failed to review PO {po_id}: {e}", exc_info=True)
        return error_response(
            code="REVIEW_FAILED",
            message="Failed to record PO review decisions",
            details={"error": str(e)}
        )


@router.post("/{list_id}/reject")
async def reject_shopping_list(
    list_id: str,
    request: ApprovalRequest,
    current_user: UserResponse = Depends(get_current_user)
):
    """
    Reject shopping list

    Args:
        list_id: MongoDB ObjectId of shopping list
        request: Rejection request with optional notes

    Returns:
        Success confirmation
    """
    if current_user.role != UserRole.ADMIN:
        return error_response(
            code="FORBIDDEN",
            message="Only administrators can reject shopping lists"
        )

    try:
        service = get_shopping_list_service()
        success = await service.reject_list(
            list_id,
            str(current_user.id),
            request.notes
        )

        if not success:
            return error_response(
                code="REJECTION_FAILED",
                message="Shopping list not found or already processed"
            )

        return success_response(
            data={"rejected": True, "list_id": list_id},
            message="Shopping list rejected"
        )

    except Exception as e:
        logger.error(f"Failed to reject shopping list {list_id}: {e}", exc_info=True)
        return error_response(
            code="REJECTION_FAILED",
            message="Failed to reject shopping list",
            details={"error": str(e)}
        )


# ── Promotion Suggestions Approval ───────────────────────────────────────────

@router.post("/promotion-suggestions/{suggestion_id}/approve")
async def approve_promotion_suggestion(
    suggestion_id: str,
    body: ApprovalRequest,
    current_user: UserResponse = Depends(get_admin_user),
):
    """
    Approve a promotion suggestion generated by the Customer Experience Agent.

    On approval:
    - Sets suggestion status to 'approved'
    - Writes an active promotion record to the `promotions` collection
      with a 1-day window (start_date = today, end_date = today)
    """
    try:
        db = get_database()
        now = now_ist()
        today_str = now.strftime("%Y-%m-%d")

        result = await db.promotion_suggestions.find_one_and_update(
            {"_id": ObjectId(suggestion_id), "status": "pending"},
            {"$set": {
                "status": "approved",
                "reviewed_at": now,
                "reviewed_by": current_user.email,
                "approval_notes": body.notes,
            }},
            return_document=True,
        )

        if not result:
            return error_response(
                code="NOT_FOUND",
                message="Promotion suggestion not found or already decided",
            )

        # Write an active promotion record so the order service can apply it
        promo_doc = {
            "promo_id": suggestion_id,  # Map for frontend compatibility
            "restaurant_id": result.get("restaurant_id"),
            "suggestion_id": suggestion_id,
            "promo_type": result.get("promo_type"),
            "menu_item_ids_array": result.get("menu_item_ids", []),
            "menu_item_names": result.get("menu_item_names", []),
            "discount_pct": result.get("discount_pct", 0),
            "description": result.get("description", ""),
            "status": "active",
            "start_date": today_str,
            "end_date": today_str,
            "created_at": now,
            "approved_by": current_user.email,
        }
        await db.promotions.insert_one(promo_doc)

        # Notify all staff about the active promotion
        from app.services.orchestrator import get_orchestrator
        await get_orchestrator()._create_notification(
            type="promotion_active",
            title="New promotion live today",
            message=result.get("description", "A new promotion is active today."),
            severity="info",
            target_roles=["admin", "waiter"],
            metadata={"suggestion_id": suggestion_id, "promo_type": result.get("promo_type")},
        )

        return success_response(
            data={"suggestion_id": suggestion_id, "status": "approved"},
            message="Promotion suggestion approved — promotion is now active",
        )

    except Exception as e:
        logger.error(f"Failed to approve promotion suggestion {suggestion_id}: {e}", exc_info=True)
        return error_response(
            code="APPROVAL_FAILED",
            message="Failed to approve promotion suggestion",
            details={"error": str(e)},
        )


@router.post("/promotion-suggestions/{suggestion_id}/reject")
async def reject_promotion_suggestion(
    suggestion_id: str,
    body: ApprovalRequest,
    current_user: UserResponse = Depends(get_admin_user),
):
    """Reject a promotion suggestion generated by the Customer Experience Agent."""
    try:
        db = get_database()
        result = await db.promotion_suggestions.find_one_and_update(
            {"_id": ObjectId(suggestion_id), "status": "pending"},
            {"$set": {
                "status": "rejected",
                "reviewed_at": now_ist(),
                "reviewed_by": current_user.email,
                "approval_notes": body.notes,
            }},
            return_document=True,
        )

        if not result:
            return error_response(
                code="NOT_FOUND",
                message="Promotion suggestion not found or already decided",
            )

        return success_response(
            data={"suggestion_id": suggestion_id, "status": "rejected"},
            message="Promotion suggestion rejected",
        )

    except Exception as e:
        logger.error(f"Failed to reject promotion suggestion {suggestion_id}: {e}", exc_info=True)
        return error_response(
            code="REJECTION_FAILED",
            message="Failed to reject promotion suggestion",
            details={"error": str(e)},
        )


# ── Delivery Receiving ────────────────────────────────────────────────────────

class DeliveryConfirmRequest(BaseModel):
    """Staff confirms delivery of ordered items."""
    material_ids: List[str] = Field(..., description="material_ids that were received")
    notes: Optional[str] = None


@router.post("/{list_id}/confirm-delivery")
async def confirm_delivery(
    list_id: str,
    request: DeliveryConfirmRequest,
    current_user: UserResponse = Depends(get_current_user),
):
    """
    Staff confirms receipt of delivered items.

    Marks the items as 'delivered' in the shopping list and updates
    inventory quantities via the inventory service.
    """
    try:
        service = get_shopping_list_service()
        shopping_list = await service.get_shopping_list(list_id)
        if not shopping_list:
            return error_response(code="NOT_FOUND", message="Shopping list not found")

        # Mark items delivered in shopping list
        await service.mark_items_delivered(list_id, request.material_ids)

        # Update inventory quantities for delivered items
        from app.services.inventory_service import get_inventory_service
        inv_service = get_inventory_service()

        items_by_id = {i["material_id"]: i for i in shopping_list.get("items", [])}
        updated_materials = []

        for material_id in request.material_ids:
            item = items_by_id.get(material_id)
            if not item:
                continue
            qty = item.get("approved_quantity") or item.get("quantity_to_order", 0)
            if qty:
                await inv_service.add_stock(material_id, qty, source="hyperpure_delivery")
                updated_materials.append(material_id)

        logger.info(
            f"Delivery confirmed for list {list_id}: "
            f"{len(updated_materials)} items, user={current_user.email}"
        )

        return success_response(
            data={
                "list_id": list_id,
                "delivered_items": len(updated_materials),
                "material_ids": updated_materials,
            },
            message=f"Delivery confirmed — {len(updated_materials)} item(s) added to inventory",
        )

    except Exception as e:
        logger.error(f"Failed to confirm delivery for list {list_id}: {e}", exc_info=True)
        return error_response(
            code="DELIVERY_FAILED",
            message="Failed to confirm delivery",
            details={"error": str(e)},
        )
