/**
 * Approvals Page - Shopping List Approval Dashboard
 *
 * Allows admins to review and approve shopping lists generated by the Inventory Agent
 */

import React, { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import SubTabNavigation from '../components/SubTabNavigation';
import ConfirmModal from '../components/ConfirmModal';
import {
  getPendingApprovals,
  getShoppingListDetails,
  approveShoppingList,
  approveShoppingListItems,
  rejectShoppingList,
  getApprovalHistory,
  getApprovalStats,
} from '../services/approvals';
import { triggerInventoryAgent } from '../services/agents';
import type {
  ShoppingList,
  ShoppingListItem,
  ApprovalStats,
  ItemUrgency,
  ShoppingListStatus,
} from '../types/approvals';
import './ApprovalsPage.css';

type TabType = 'pending' | 'history' | 'stats';

const ApprovalsPage: React.FC = () => {
  const { user } = useAuth();

  // Tab state
  const [activeTab, setActiveTab] = useState<TabType>('pending');

  // Pending lists state
  const [pendingLists, setPendingLists] = useState<ShoppingList[]>([]);
  const [selectedList, setSelectedList] = useState<ShoppingList | null>(null);
  const [selectedItems, setSelectedItems] = useState<Set<string>>(new Set());

  // History state
  const [historyLists, setHistoryLists] = useState<ShoppingList[]>([]);
  const [historyPage, setHistoryPage] = useState(1);
  const [historyTotal, setHistoryTotal] = useState(0);
  const [historyStatus, setHistoryStatus] = useState<ShoppingListStatus | ''>('');

  // Stats state
  const [stats, setStats] = useState<ApprovalStats | null>(null);

  // UI state
  const [loading, setLoading] = useState(false);
  const [triggeringInventoryAgent, setTriggeringInventoryAgent] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notes, setNotes] = useState('');
  const [showConfirmModal, setShowConfirmModal] = useState(false);
  const [confirmAction, setConfirmAction] = useState<'approve' | 'reject' | 'partial' | null>(
    null
  );

  // Load data on mount and tab change
  useEffect(() => {
    if (activeTab === 'pending') {
      loadPendingApprovals();
    } else if (activeTab === 'history') {
      loadApprovalHistory();
    } else if (activeTab === 'stats') {
      loadApprovalStats();
    }
  }, [activeTab, historyPage, historyStatus]);

  // Reload selected list details when selectedList._id changes
  useEffect(() => {
    if (selectedList) {
      loadListDetails(selectedList._id);
    }
  }, []);

  // API calls
  const loadPendingApprovals = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await getPendingApprovals();
      setPendingLists(response.data);
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Failed to load pending approvals');
    } finally {
      setLoading(false);
    }
  };

  const loadListDetails = async (listId: string) => {
    setLoading(true);
    setError(null);
    try {
      const response = await getShoppingListDetails(listId);
      setSelectedList(response.data);
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Failed to load shopping list details');
    } finally {
      setLoading(false);
    }
  };

  const loadApprovalHistory = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await getApprovalHistory({
        page: historyPage,
        limit: 20,
        status: historyStatus || undefined,
      });
      setHistoryLists(response.data);
      setHistoryTotal(response.pagination.total);
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Failed to load approval history');
    } finally {
      setLoading(false);
    }
  };

  const loadApprovalStats = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await getApprovalStats();
      setStats(response.data);
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Failed to load approval statistics');
    } finally {
      setLoading(false);
    }
  };

  // Action handlers
  const handleTriggerInventoryAgent = async () => {
    setTriggeringInventoryAgent(true);
    setError(null);
    try {
      await triggerInventoryAgent();
      alert('Inventory agent triggered. New shopping list will appear if low stock items are found.');
      await loadPendingApprovals();
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Failed to trigger inventory agent');
    } finally {
      setTriggeringInventoryAgent(false);
    }
  };

  const handleApproveList = () => {
    setConfirmAction('approve');
    setShowConfirmModal(true);
  };

  const handleRejectList = () => {
    setConfirmAction('reject');
    setShowConfirmModal(true);
  };

  const handlePartialApprove = () => {
    if (selectedItems.size === 0) {
      alert('Please select at least one item to approve');
      return;
    }
    setConfirmAction('partial');
    setShowConfirmModal(true);
  };

  const handleConfirmAction = async () => {
    if (!selectedList || !confirmAction) return;

    setLoading(true);
    setError(null);
    setShowConfirmModal(false);

    try {
      if (confirmAction === 'approve') {
        await approveShoppingList(selectedList._id, { notes: notes || undefined });
        alert('Shopping list approved successfully');
      } else if (confirmAction === 'reject') {
        await rejectShoppingList(selectedList._id, { notes: notes || undefined });
        alert('Shopping list rejected');
      } else if (confirmAction === 'partial') {
        await approveShoppingListItems(selectedList._id, {
          material_ids: Array.from(selectedItems),
          notes: notes || undefined,
        });
        alert(`Approved ${selectedItems.size} items`);
      }

      // Reset state
      setNotes('');
      setSelectedItems(new Set());
      setSelectedList(null);
      setConfirmAction(null);

      // Reload pending lists
      loadPendingApprovals();
    } catch (err: any) {
      setError(err.response?.data?.error?.message || 'Action failed');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleItem = (materialId: string) => {
    const newSelection = new Set(selectedItems);
    if (newSelection.has(materialId)) {
      newSelection.delete(materialId);
    } else {
      newSelection.add(materialId);
    }
    setSelectedItems(newSelection);
  };

  const handleSelectAll = () => {
    if (!selectedList) return;
    const allMaterialIds = selectedList.items.map((item) => item.material_id);
    setSelectedItems(new Set(allMaterialIds));
  };

  const handleDeselectAll = () => {
    setSelectedItems(new Set());
  };

  // Helper functions
  const formatCurrency = (amountInPaise: number): string => {
    return `₹${(amountInPaise / 100).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  };

  const formatDate = (dateString: string): string => {
    return new Date(dateString).toLocaleString('en-IN', {
      dateStyle: 'medium',
      timeStyle: 'short',
    });
  };

  const getUrgencyBadgeClass = (urgency: ItemUrgency): string => {
    switch (urgency) {
      case 'URGENT':
        return 'urgency-badge-urgent';
      case 'STANDARD':
        return 'urgency-badge-standard';
      case 'LOW_PRIORITY':
        return 'urgency-badge-low';
      default:
        return '';
    }
  };

  const getStatusBadgeClass = (status: ShoppingListStatus): string => {
    switch (status) {
      case 'pending':
        return 'status-badge-pending';
      case 'approved':
        return 'status-badge-approved';
      case 'rejected':
        return 'status-badge-rejected';
      case 'partially_approved':
        return 'status-badge-partial';
      default:
        return '';
    }
  };

  // Render functions
  const renderPendingTab = () => {
    if (selectedList) {
      return renderListDetails();
    }

    return (
      <div className="pending-lists">
        <div className="section-header section-header-with-action">
          <div>
            <h2>Pending Shopping Lists</h2>
            <p className="subtitle">Review and approve shopping lists generated by the Inventory Agent</p>
          </div>
          <button
            type="button"
            className="btn-trigger-agent"
            onClick={handleTriggerInventoryAgent}
            disabled={loading || triggeringInventoryAgent}
          >
            {triggeringInventoryAgent ? 'Running Inventory Agent...' : 'Run Inventory Agent'}
          </button>
        </div>

        {pendingLists.length === 0 ? (
          <div className="empty-state">
            <p>No pending shopping lists</p>
            <p className="empty-state-subtitle">All caught up! 🎉</p>
          </div>
        ) : (
          <div className="lists-grid">
            {pendingLists.map((list) => (
              <div
                key={list._id}
                className="list-card"
                onClick={() => setSelectedList(list)}
              >
                <div className="list-card-header">
                  <h3>{list.list_id}</h3>
                  <span className={`status-badge ${getStatusBadgeClass(list.status)}`}>
                    {list.status}
                  </span>
                </div>

                <div className="list-card-meta">
                  <p className="list-date">{formatDate(list.generated_at)}</p>
                  <p className="list-cost">{formatCurrency(list.total_cost_inr)}</p>
                </div>

                <div className="urgency-summary">
                  {list.urgency_summary.urgent_count > 0 && (
                    <span className="urgency-badge urgency-badge-urgent">
                      {list.urgency_summary.urgent_count} URGENT
                    </span>
                  )}
                  {list.urgency_summary.standard_count > 0 && (
                    <span className="urgency-badge urgency-badge-standard">
                      {list.urgency_summary.standard_count} STANDARD
                    </span>
                  )}
                  {list.urgency_summary.low_priority_count > 0 && (
                    <span className="urgency-badge urgency-badge-low">
                      {list.urgency_summary.low_priority_count} LOW
                    </span>
                  )}
                </div>

                <div className="list-card-footer">
                  <p className="item-count">{list.items.length} items</p>
                  <p className="confidence-score">
                    Confidence: {(list.confidence_score * 100).toFixed(0)}%
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  };

  const renderListDetails = () => {
    if (!selectedList) return null;

    return (
      <div className="list-details">
        <div className="details-header">
          <button className="back-button" onClick={() => setSelectedList(null)}>
            ← Back to Pending Lists
          </button>

          <div className="details-title">
            <h2>{selectedList.list_id}</h2>
            <span className={`status-badge ${getStatusBadgeClass(selectedList.status)}`}>
              {selectedList.status}
            </span>
          </div>

          <div className="details-meta">
            <p>Generated: {formatDate(selectedList.generated_at)}</p>
            <p>Total Cost: <strong>{formatCurrency(selectedList.total_cost_inr)}</strong></p>
            <p>Confidence: {(selectedList.confidence_score * 100).toFixed(0)}%</p>
          </div>

          <div className="agent-reasoning">
            <h4>Agent Reasoning:</h4>
            <p>{selectedList.reasoning}</p>
          </div>
        </div>

        {/* Item selection controls */}
        <div className="selection-controls">
          <div className="selection-info">
            {selectedItems.size > 0 && (
              <span className="selected-count">{selectedItems.size} items selected</span>
            )}
          </div>
          <div className="selection-buttons">
            <button onClick={handleSelectAll} className="btn-secondary">
              Select All
            </button>
            <button onClick={handleDeselectAll} className="btn-secondary">
              Deselect All
            </button>
          </div>
        </div>

        {/* Items table */}
        <div className="items-table-container">
          <table className="items-table">
            <thead>
              <tr>
                <th>Select</th>
                <th>Item</th>
                <th>Current Stock</th>
                <th>Daily Demand</th>
                <th>Days Until Stockout</th>
                <th>Quantity to Order</th>
                <th>Cost</th>
                <th>Urgency</th>
                <th>Supplier</th>
              </tr>
            </thead>
            <tbody>
              {selectedList.items.map((item) => (
                <tr key={item.material_id} className={selectedItems.has(item.material_id) ? 'selected-row' : ''}>
                  <td>
                    <input
                      type="checkbox"
                      checked={selectedItems.has(item.material_id)}
                      onChange={() => handleToggleItem(item.material_id)}
                    />
                  </td>
                  <td>
                    <strong>{item.material_name}</strong>
                    <br />
                    <small>{item.material_id}</small>
                  </td>
                  <td>{item.current_stock}</td>
                  <td>{item.daily_demand.toFixed(1)}</td>
                  <td>
                    <span className={item.days_until_stockout <= 2 ? 'critical-stockout' : ''}>
                      {item.days_until_stockout.toFixed(1)} days
                    </span>
                  </td>
                  <td>{item.quantity_to_order}</td>
                  <td>{formatCurrency(item.line_total_inr)}</td>
                  <td>
                    <span className={`urgency-badge ${getUrgencyBadgeClass(item.urgency)}`}>
                      {item.urgency}
                    </span>
                    <br />
                    <small className="urgency-reason">{item.urgency_reason}</small>
                  </td>
                  <td>
                    {item.supplier_name}
                    <br />
                    <small>Lead time: {item.lead_time_days} days</small>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Supplier breakdown */}
        <div className="supplier-breakdown">
          <h3>Supplier Breakdown</h3>
          <div className="supplier-grid">
            {selectedList.supplier_breakdown.map((supplier) => (
              <div key={supplier.supplier_id} className="supplier-card">
                <h4>{supplier.supplier_name}</h4>
                <p className="supplier-meta">
                  {supplier.item_count} items · {formatCurrency(supplier.total_cost_inr)}
                </p>
                <div className="supplier-items">
                  {supplier.items.map((materialId) => {
                    const item = selectedList.items.find((i) => i.material_id === materialId);
                    return item ? (
                      <span key={materialId} className="supplier-item-tag">
                        {item.material_name}
                      </span>
                    ) : null;
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Notes input */}
        <div className="notes-section">
          <label htmlFor="approval-notes">Notes (optional):</label>
          <textarea
            id="approval-notes"
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Add notes about this approval decision..."
            rows={3}
          />
        </div>

        {/* Action buttons */}
        <div className="action-buttons">
          <button onClick={handleApproveList} className="btn-approve">
            Approve Entire List
          </button>
          <button
            onClick={handlePartialApprove}
            className="btn-partial"
            disabled={selectedItems.size === 0}
          >
            Approve Selected Items ({selectedItems.size})
          </button>
          <button onClick={handleRejectList} className="btn-reject">
            Reject List
          </button>
        </div>
      </div>
    );
  };

  const renderHistoryTab = () => {
    const totalPages = Math.ceil(historyTotal / 20);

    return (
      <div className="history-tab">
        <div className="section-header">
          <h2>Approval History</h2>
          <p className="subtitle">Audit log of all approval decisions</p>
        </div>

        {/* Filters */}
        <div className="history-filters">
          <label>
            Status:
            <select
              value={historyStatus}
              onChange={(e) => {
                setHistoryStatus(e.target.value as ShoppingListStatus | '');
                setHistoryPage(1);
              }}
            >
              <option value="">All</option>
              <option value="approved">Approved</option>
              <option value="rejected">Rejected</option>
              <option value="partially_approved">Partially Approved</option>
              <option value="pending">Pending</option>
            </select>
          </label>
        </div>

        {/* History table */}
        {historyLists.length === 0 ? (
          <div className="empty-state">
            <p>No approval history found</p>
          </div>
        ) : (
          <>
            <table className="history-table">
              <thead>
                <tr>
                  <th>List ID</th>
                  <th>Generated</th>
                  <th>Status</th>
                  <th>Items</th>
                  <th>Total Cost</th>
                  <th>Reviewed</th>
                  <th>Notes</th>
                </tr>
              </thead>
              <tbody>
                {historyLists.map((list) => (
                  <tr key={list._id}>
                    <td><strong>{list.list_id}</strong></td>
                    <td>{formatDate(list.generated_at)}</td>
                    <td>
                      <span className={`status-badge ${getStatusBadgeClass(list.status)}`}>
                        {list.status}
                      </span>
                    </td>
                    <td>{list.items.length}</td>
                    <td>{formatCurrency(list.total_cost_inr)}</td>
                    <td>
                      {list.reviewed_at ? (
                        <>
                          {formatDate(list.reviewed_at)}
                          <br />
                          <small>by {list.reviewed_by}</small>
                        </>
                      ) : (
                        'Not reviewed'
                      )}
                    </td>
                    <td className="notes-cell">{list.approval_notes || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            {/* Pagination */}
            <div className="pagination">
              <button
                onClick={() => setHistoryPage((p) => Math.max(1, p - 1))}
                disabled={historyPage === 1}
              >
                Previous
              </button>
              <span>
                Page {historyPage} of {totalPages}
              </span>
              <button
                onClick={() => setHistoryPage((p) => Math.min(totalPages, p + 1))}
                disabled={historyPage === totalPages}
              >
                Next
              </button>
            </div>
          </>
        )}
      </div>
    );
  };

  const renderStatsTab = () => {
    if (!stats) return null;

    return (
      <div className="stats-tab">
        <div className="section-header">
          <h2>Approval Statistics</h2>
          <p className="subtitle">Overview of shopping list approval metrics</p>
        </div>

        <div className="stats-grid">
          <div className="stat-card stat-pending">
            <h3>{stats.pending}</h3>
            <p>Pending</p>
          </div>
          <div className="stat-card stat-approved">
            <h3>{stats.approved}</h3>
            <p>Approved</p>
          </div>
          <div className="stat-card stat-rejected">
            <h3>{stats.rejected}</h3>
            <p>Rejected</p>
          </div>
          <div className="stat-card stat-partial">
            <h3>{stats.partially_approved}</h3>
            <p>Partially Approved</p>
          </div>
          <div className="stat-card stat-total">
            <h3>{stats.total}</h3>
            <p>Total Lists</p>
          </div>
        </div>

        {stats.total > 0 && (
          <div className="stats-chart">
            <h3>Approval Breakdown</h3>
            <div className="chart-bars">
              <div className="chart-bar">
                <div
                  className="bar-fill bar-approved"
                  style={{ width: `${(stats.approved / stats.total) * 100}%` }}
                />
                <span className="bar-label">
                  Approved: {((stats.approved / stats.total) * 100).toFixed(1)}%
                </span>
              </div>
              <div className="chart-bar">
                <div
                  className="bar-fill bar-rejected"
                  style={{ width: `${(stats.rejected / stats.total) * 100}%` }}
                />
                <span className="bar-label">
                  Rejected: {((stats.rejected / stats.total) * 100).toFixed(1)}%
                </span>
              </div>
              <div className="chart-bar">
                <div
                  className="bar-fill bar-partial"
                  style={{ width: `${(stats.partially_approved / stats.total) * 100}%` }}
                />
                <span className="bar-label">
                  Partial: {((stats.partially_approved / stats.total) * 100).toFixed(1)}%
                </span>
              </div>
              <div className="chart-bar">
                <div
                  className="bar-fill bar-pending"
                  style={{ width: `${(stats.pending / stats.total) * 100}%` }}
                />
                <span className="bar-label">
                  Pending: {((stats.pending / stats.total) * 100).toFixed(1)}%
                </span>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  };

  // Main render
  return (
    <div className="approvals-page">
      <div className="approvals-container">
        <header className="approvals-header">
          <h1>Shopping List Approvals</h1>
          <p>Review and approve inventory orders generated by the AI agent</p>
        </header>

        {error && (
          <div className="error-banner">
            <span>⚠️ {error}</span>
            <button onClick={() => setError(null)}>×</button>
          </div>
        )}

        {loading && <div className="loading-spinner">Loading...</div>}

        <SubTabNavigation
          tabs={[
            { id: 'pending', label: 'Pending' },
            { id: 'history', label: 'History' },
            { id: 'stats', label: 'Statistics' },
          ]}
          activeTab={activeTab}
          onTabChange={(tab) => setActiveTab(tab as TabType)}
        />

        <div className="tab-content">
          {activeTab === 'pending' && renderPendingTab()}
          {activeTab === 'history' && renderHistoryTab()}
          {activeTab === 'stats' && renderStatsTab()}
        </div>
      </div>

      {/* Confirmation modal */}
      {showConfirmModal && (
        <ConfirmModal
          title={
            confirmAction === 'approve'
              ? 'Approve Shopping List?'
              : confirmAction === 'reject'
              ? 'Reject Shopping List?'
              : `Approve ${selectedItems.size} Items?`
          }
          message={
            confirmAction === 'approve'
              ? `Are you sure you want to approve this shopping list for ${formatCurrency(
                  selectedList?.total_cost_inr || 0
                )}?`
              : confirmAction === 'reject'
              ? 'Are you sure you want to reject this shopping list?'
              : `Are you sure you want to approve ${selectedItems.size} selected items?`
          }
          onConfirm={handleConfirmAction}
          onCancel={() => {
            setShowConfirmModal(false);
            setConfirmAction(null);
          }}
          confirmText={confirmAction === 'reject' ? 'Reject' : 'Approve'}
          cancelText="Cancel"
        />
      )}
    </div>
  );
};

export default ApprovalsPage;
